import { Duplex, PassThrough } from 'readable-stream'
import JsonEventStream from '../index.js'

async function main () {
  // create a Duplex stream with input/output for reading and writing
  const input = new PassThrough()
  const output = new PassThrough()
  const stream = Duplex.from({ writable: output, readable: input })

  // create the JsonEventStream object using the Duplex stream
  const events = new JsonEventStream(stream)

  // add an event listener for from-json events generated from JSON objects
  events.on('from-json', (...arg) => {
    console.log(`from-json: ${JSON.stringify(arg)}`)
  })

  // write a JSON object that emits a from-json event with an argument
  input.write('{"event": "from-json", "arguments": ["test"]}\n')

  // pipe the JSON stream generated by events to stdout
  output.pipe(process.stdout)

  // and emit an event that generates a JSON object
  events.emit('from-event', 'test')
}

main()
